### ISSUE TITLE
Лишние пробелы

### ISSUE THREAD

**Issue by TimScriptov** [massivemadness/Squircle-CE#105]
Если открыть файл с кодом и свернуть приложение, появляются не существовующие пробелы.

До:
![Screenshot_20211116_211734_com.blacksquircle.ui.jpg](https://user-images.githubusercontent.com/31324315/142023757-8357bddb-e196-44c5-9145-6af18dd0509a.jpg)

После:
![Screenshot_20211116_211739_com.blacksquircle.ui.jpg](https://user-images.githubusercontent.com/31324315/142023808-82836dee-0459-4838-90e6-2b236d49ffa7.jpg)

Если занова открыть документ, пробелы отсутствуют

**Comment by TimScriptov** [comment]
Также редактор довольно сильно тормозит, особенно при выделении кода.

**Comment by massivemadness** [comment]
Насчет пробелов поизучаю, про тормоза мне известно. Есть два коммита aec135821f6efb2ada33cae72d5f056903cc52fe и 80daa5f80bf5cb78a111ea20d490837ec2cbd23a, суть в том, что если не стирать видимые спаны то всё работает раза в 2-3 быстрее, но тогда появляются артефакты/лишние спаны которых быть не должно. Если есть идеи как можно исправить, буду признателен 🙃

**Comment by TimScriptov** [comment]
@massivemadness не, в редакторах не шарю. Использовал только чужие реализации
