### ISSUE TITLE
add a save button on down!

### ISSUE THREAD

**Issue by mablue** [massivemadness/Squircle-CE#111]
hi some times i change the code 1000 times and switch between termux and code editor so
its really hard to reach to the top of phone each time for one who have small fingers like me!
![samandon-2-ir2day](https://user-images.githubusercontent.com/5004900/152800264-1a356e74-97d2-4f84-8ad3-ffbee426c16d.jpg)

**Describe the solution you'd like**

I need to have a save button right under my fingers top of the keyboard to save time and keep my own younger!:)
thanks

**Describe alternatives you've considered**
see Acode editor

**Comment by Ilithy** [comment]
What would be fantastic, it would be to have all the option bar and tab selection (see screenshot) at the bottom, on smartphones with a large screen +6.5" it's extremely practical, it avoids having to move your hands every time you change tabs, save, open a new file ..., it makes the work much smoother and faster, I'd love to see this in Squircle IDE, it's one of the few shortcomings of this great application.

**Comment by mablue** [comment]
Thanks man I will use it Now 🫡🕺

**Comment by mablue** [comment]
https://github.com/massivemadness/Squircle-CE/issues/181#issue-1620429294
