### ISSUE TITLE
Smooth cursor movement

### ISSUE THREAD

**Issue by Francis-96** [massivemadness/Squircle-CE#117]
refer to this project `https://github.com/Rosemoe/sora-editor`

**1.** Cursor smooth movement effect
[Comparison video 1](https://github.com/Francis-96/Demo/blob/main/Cursor%20smooth%20movement%20effect.mp4)

**2.** When the content slides to the bottom to leave a blank area of ​​the keyboard height, because the keyboard pops up to push the content up, the content will bounce back when the keyboard disappears, resulting in instant screen flickering, this experience is too bad
[Comparison video 2](https://github.com/Francis-96/Demo/blob/main/leave%20the%20bottom%20blank.mp4)

**Comment by massivemadness** [comment]
Hi @Francis-96, It's almost impossible to achieve this behaviour using the `EditText` component. Sora Editor uses fully custom view which makes this a lot easier and faster, and I don't have much time to try to make the same 😔
I'll leave this issue opened, maybe one day there will be an easier way to create things like that, but now I don't see it.
