### ISSUE TITLE
Unable to parse unsupported language 

### ISSUE THREAD

**Issue by capitalstep** [massivemadness/Squircle-CE#123]
![Screenshot_20220526-225913_Squircle IDE](https://user-images.githubusercontent.com/20308876/170620477-350ffec5-caee-4a26-a7a6-9f0ebc317175.jpg)
Not sure what I've done wrong here but the app is unable to parse when attempting to error check. It says unsupported language.

**Comment by capitalstep** [comment]
Just read about the parser being limited to javascript only.

**Comment by GyanPrakash2483** [comment]
It only works for javascript

**Comment by massivemadness** [comment]
Just released [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.0) where I completely removed error checking. It'll be rewritten from scratch in the future due to large amount of problems
