### ISSUE TITLE
error checker broken

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [massivemadness/Squircle-CE#133]
![Screenshot_20220623-230758.jpg](https://user-images.githubusercontent.com/41585567/175400116-301a9a02-3470-476a-a1f7-1fc944a8e06f.jpg)

![Screenshot_20220623-230741.jpg](https://user-images.githubusercontent.com/41585567/175400258-a0336b3e-6c6c-4c5a-9606-db062c75d54f.jpg)

tools error checker said error but my script seem don,t have error he work perfect

thanks

**Comment by massivemadness** [comment]
Just released [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.0) where I completely removed error checking. It'll be rewritten from scratch in the future due to large amount of problems
