### ISSUE TITLE
file panel toggle doesnt work in landscape mode

### ISSUE THREAD

**Issue by xxjoe2** [massivemadness/Squircle-CE#135]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
Release v2022.1.2, v2.2.0

**Affected Device(s):**
samaung tablet

**Describe the bug**
file panel wont hide in landscape mode

**To Reproduce**
1. in port mode
2. press menu button toggles the file panel
3. switch to landscape mode, nothing happens with the file panel always open

**Expected behavior**
toggle to hide (or open) the file panel in landscape mode

**Comment by massivemadness** [comment]
Hi @xxjoe2, can you attach screenshot or video?
