### ISSUE TITLE
Read Only Mode

### ISSUE THREAD

**Issue by NetworkWebMasters** [massivemadness/Squircle-CE#141]
Please add read only mode when opening any file.

**Comment by massivemadness** [comment]
Read-only mode was present in older versions of the editor, but nobody used it so I decided to remove it. But I may bring it back in the next version

**Comment by NetworkWebMasters** [comment]
Thank you so much for your reply, Read only mode is very useful to people if they want to study the code, i prefer read only mode while studying the code, because it wont open keyboard if i click any where while scrolling page. Its very very useful feature.

**Comment by NetworkWebMasters** [comment]
Please check Solid Explorer feature on Google Play Store https://play.google.com/store/apps/details?id=pl.solidexplorer2

It opens zip file directly without extracting, its useful feature when people dont want to extract zip and read files coding directly in zip file.

**Comment by NetworkWebMasters** [comment]
Any update on read only mode?

**Comment by NetworkWebMasters** [comment]
Please add read only mode.

**Comment by NetworkWebMasters** [comment]
Thank you so much for your smile reaction.
I uninstalled this app.

**Comment by massivemadness** [comment]
Hi @NetworkWebMasters, I remember your request, but I've had other priorities for the first few releases this year

**Comment by massivemadness** [comment]
Added in [v2023.1.4](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.4)
