### ISSUE TITLE
Not working ROOT directory 

### ISSUE THREAD

**Issue by try-man** [massivemadness/Squircle-CE#142]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
2022.2.0

**Affected Device(s):**
Redmi Note 10 Pro

**Describe the bug**
I choose the root directory, the application does not request root dotsup, as a result, you can not read / change files.

**Expected behavior**
Full read/modify access to the root directory.

**Comment by massivemadness** [comment]
Hi @try-man , today I'll release an update, you can already check [this](https://github.com/massivemadness/Squircle-CE/actions/runs/3183742102) build

**Comment by massivemadness** [comment]
Ok, but zip4j will not work properly with root files, so I disabled compress/extract actions
