### ISSUE TITLE
Difference between "Squircle CE" and "Brackeys IDE"?

### ISSUE THREAD

**Issue by just-Nob** [massivemadness/Squircle-CE#143]
Can anyone please give me any information about the difference between those two apps?
Both look very similar.

By searching the issues, I found "Brackeys IDE" in issue #63, so I'm guessing that "Brackeys IDE" is a branch of "Squircle CE"?

**Comment by massivemadness** [comment]
Squircle CE previously was known as Brackeys IDE, but I had to change the app name because of the copyright issues

![IMG_20221006_145048](https://user-images.githubusercontent.com/7825871/194305510-f4d651a3-0a75-4e7e-96ec-1ea6a9ad4ec8.jpg)

**Comment by just-Nob** [comment]
Hi @massivemadness,

thanks for clarifying!!
