### ISSUE TITLE
Option to disable automatic Line Break

### ISSUE THREAD

**Issue by just-Nob** [massivemadness/Squircle-CE#145]
**Current Behaviour:**
Currently, the code's lines being too long to be displayed in one row will be automatically broken into a second (third, fourth etc.) line/row.
A side effect is that the code is always only vertically scrollable.

**Desired Option:**
I found it very helpful to have the possibility to optionally switch off the automatic line break, so that every line fits in a single row.
To view the whole code in that mode, it had to be possible to scroll both vertical _as well as **horizontal**_.

**Comment by massivemadness** [comment]
Hi @just-Nob , such option already exists in Settings > Editor > Word Wrap

**Comment by just-Nob** [comment]
Thanks @massivemadness,
thanks a lot for that hint.

I haven't found that option because the app runs in the phone's language (I guess there's no option to change that?), which in my case is German.

Unfortunately, in my opinion the German translation (as well as the option's description) of "Word Wrap" is a little bit... - let's say 'unusual'.
Is the translation done by automated translation (like Google translate, deepl.com or something similar)?
If so, is there a way to rework & complete the translation "by hand"?

**Comment by massivemadness** [comment]
@just-Nob Sure, you can make PR that changes the translation in `strings.xml` file. Each gradle module has it's own translation file, so if you want to change something else, make changes in other `strings.xml`
https://github.com/massivemadness/Squircle-CE/blob/master/feature-settings/src/main/res/values-de/strings.xml
