### ISSUE TITLE
Is this a fork of "Brackeys IDE"? 

### ISSUE THREAD

**Issue by 825i** [massivemadness/Squircle-CE#146]
Brackeys IDE was discontinued on 2021.2.1. It had the same design, same app icon even and was also FOSS. I've kept it on my phone for years and used it without issues or updates.

I just came across this app. Is this a fork, or such?

I'm just genuinely curious. Because I always wished they had continued development on Brackeys IDE. If it is a fork, can I ask why this is mentioned absolutely nowhere?

Edit: I find it very interesting, that the latest version of this app is listed as 2022.2.1 and the last version of Brackeys IDE was 2021.2.1

https://archive.org/details/com.brackeys.ui_10002

![Screenshot_20221012_015048](https://user-images.githubusercontent.com/58630825/195212688-0426de6f-a729-4d88-a22a-e16a6630ed3c.jpg)

**Comment by 825i** [comment]
Nevermind. I should have looked harder.

Wow. I can actually uninstall the 1 year and 10 month old app I had and make use of this one with all the changes. Happy days!

![Screenshot_20221012_015853](https://user-images.githubusercontent.com/58630825/195213598-7c4d7d05-a401-4055-af54-458a97d9dd58.jpg)

**Comment by massivemadness** [comment]
Hi @825i, yes, it's just rebranding. There's an issue where I described it in more details #143
