### ISSUE TITLE
Full-text search in the project directory

### ISSUE THREAD

**Issue by opk12** [massivemadness/Squircle-CE#149]
**Is your feature request related to a problem? Please describe.**
I want to search for a string in all files of the project directory at once.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Opening each file manually and hitting the next result button is cumbersome.

**Additional context**
N/A

**Comment by massivemadness** [comment]
Squircle doesn't have a "project" entity, it's just a file tree that doesn't have to be located in local storage. The elapsed time may vary when searching in a large directory or using a remote filesystem, so I wouldn't make such feature at least not until we have a project-based filesystem.
