### ISSUE TITLE
[feature request] Light theme

### ISSUE THREAD

**Issue by opk12** [massivemadness/Squircle-CE#151]
**Is your feature request related to a problem? Please describe.**
I prefer a light theme, but the app always has a dark theme.

**Describe the solution you'd like**
A light theme can be chosen in the app.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by xmha97** [comment]
+1
I need this feature.

**Comment by massivemadness** [comment]
Added in [v2023.1.2](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.2)
