### ISSUE TITLE
Change in screen orientation/rotation causes new tab to be opened with active file.

### ISSUE THREAD

**Issue by quartertone** [massivemadness/Squircle-CE#159]
Change in screen orientation/rotation causes new tab to be opened with active file.

**App Version:**
2022.2.1 (10013)

**Affected Device(s):**
Oneplus 8T, Android 11

**Describe the bug**
If a file/document is opened into Squircle by using the "Open With" dialog, changing the screen orientation (ie rotating the device) causes a new tab to be created with the active file. This only occurs when the Squircle app is not already open in the background.

**To Reproduce**
1. Close running instance of Squircle and remove it from the recent apps list.
2. From any file manager app select a text file and "Open with" Squircle
3. Rotate the screen

Result: A new tab is created with the recently opened file each time screen orientation changes.

**Expected behavior**
Screen rotation should not create a new tab with the recently opened file.

**Comment by massivemadness** [comment]
Fixed in [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.0)
Thanks for report 👍
