### ISSUE TITLE
App crashes after opening long file

### ISSUE THREAD

**Issue by HAKANKOKCU** [massivemadness/Squircle-CE#161]
**App Version:**
2022.2.1

**Affected Device(s):**
Samsung SM-N910C, Android 6.0.1

**Describe the bug**
App crashes after some seconds after opening a long file

**To Reproduce**
Steps to reproduce the behavior
1. When you enter editor, open a long file (65KB)
2. Wait a few seconds
3. And it will just close itself or crash

Here is a video:

https://user-images.githubusercontent.com/103432992/213743036-6da814db-915f-4102-be5b-7426e579778e.mp4

**Expected behavior**
i should be able to edit or view file but it crashes

**Comment by massivemadness** [comment]
Hi @HAKANKOKCU, can you attach log file?

**Comment by HAKANKOKCU** [comment]
> Hi @HAKANKOKCU, can you attach log file?

i dont know if this was the correct way but here you go:
[bugreport (no emails).txt](https://github.com/massivemadness/Squircle-CE/files/10471559/bugreport.no.emails.txt)

i had to remove my emails to not get spammed (they are " (sorry i had to hide this to not get spammed by bots) ")

**Comment by massivemadness** [comment]
@HAKANKOKCU Sorry for the long answer, this is an internal bug in error checking. You can disable it in Settings > Editor

**Comment by massivemadness** [comment]
Just released [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.0) where I completely removed error checking. It'll be rewritten from scratch in the future due to large amount of problems
