### ISSUE TITLE
How to write a plugin?

### ISSUE THREAD

**Issue by badduck32** [massivemadness/Squircle-CE#164]
Not really a bug or a feature request, but how can I write a plugin for Squircle CE? I made a fork for the editor with my features included but I think it is more useful for me and other users if I write it as a plugin, and from what I understand there is support for this (https://github.com/massivemadness/Squircle-CE#custom-plugin).

If anyone could point me in a direction on how I can get started writing a plugin, it would be greatly appreciated.

After I understand how, I could also write a little guide and create a PR with the guide included to help other people that want to create a plugin like me, if there's any interest in such a guide

Kind regards

**Comment by massivemadness** [comment]
Hi @badduck32, these [plugins](https://github.com/massivemadness/Squircle-CE/tree/master/editorkit/src/main/kotlin/com/blacksquircle/ui/editorkit/plugin) are made for an android library to extend the functionality of `TextProcessor` class, and cannot be imported dynamically into the app. The idea is to use composition over inheritance, which gives you more flexibility in the development process. Currently, there is no way to create plugins like in JetBrains products.

**Comment by badduck32** [comment]
Would it be possible to create a plugin system using this API then? I imagine you are quite busy with the editor and it's not high up on the priority list, so I can try making it once I learn more about app development.

**Comment by massivemadness** [comment]
It's possible, but not in the current state of development. I have a few ideas and it will require a lot of refactoring and API proposal, so it's low priority

**Comment by badduck32** [comment]
hmm okay so it seems currently the best way to add functionality to the editor is by forking it. Thanks for your answers!

**Comment by bitsnaps** [comment]
The only thing made me use [acode](https://f-droid.org/en/packages/com.foxdebug.acode/) is plugins system. I really wish you best of success guys.
