### ISSUE TITLE
Menus is light on dark mode

### ISSUE THREAD

**Issue by xmha97** [massivemadness/Squircle-CE#172]
Hi,
The app theme is dark but the menu is light.
Please fix this issue.
Thanks 🙏

![Screenshot_2023-03-10-21-12-06-315_com.blacksquircle.ui.jpg](https://user-images.githubusercontent.com/23485114/224389102-612fb791-8724-4ec2-a22e-c6281de41f86.jpg)

**Comment by massivemadness** [comment]
It's intentional behavior, but I can change it if it will look good 🤔

**Comment by xmha97** [comment]
Why is this behavior intentional?

**Comment by Shamaoke** [comment]
+1 👍
It would be great if the color of menus matched the color theme.

**Comment by massivemadness** [comment]
Fixed in [v2023.1.5](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.5)
