### ISSUE TITLE
feature: please consider adding sftp public key authentication method.

### ISSUE THREAD

**Issue by jnguk** [massivemadness/Squircle-CE#180]
*Please consider making a Pull Request if you are capable of doing so.*

**Describe the solution you'd like**
public key authentication is recommended for security.
Please consider adding sftp public key authentication method.

**Comment by massivemadness** [comment]
Added in [v2023.1.3](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.3)

**Comment by jnguk** [comment]
Thank you for prompt update! Could I bother you with one more thing?

The app is requesting a private key in PEM format, but it is filtering out the `.pem` extension as not selectable.
If I remove `.pem` extension manually, it works fine with the private key.

Could I request an improvement on this issue to you?
Since I'm already using it successfully, I would appreciate it if you could add it to your lower-priority improvement list.

**Comment by massivemadness** [comment]
Sure, I can send you the debug build when it's ready

**Comment by jnguk** [comment]
Wow! It works like charm. Thank you for the quick patch!

**Comment by massivemadness** [comment]
Fixed in [v2023.1.4](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.4)
