### ISSUE TITLE
remove the anti-functions in f-droid, please

### ISSUE THREAD

**Issue by Wjxfi** [massivemadness/Squircle-CE#182]

**Comment by massivemadness** [comment]
It's due to the fact that this project uses 1 library by Google
https://github.com/massivemadness/Squircle-CE/blob/master/app/build.gradle#L101
If I remove it users will not receive updates in time

**Comment by massivemadness** [comment]
Hi, that google library is not included in the fdroid [build.gradle](https://github.com/massivemadness/Squircle-CE/blob/master/app/build.gradle#L101). So there's nothing to worry about

**Comment by massivemadness** [comment]
Not exactly, it's because google play and fdroid versions are different

<img width="678" src="https://github.com/massivemadness/Squircle-CE/assets/7825871/1175e49d-5ed7-46f0-b714-2661a6111b44">
