### ISSUE TITLE
sftp connection with default rsa-keygen generated privatekey

### ISSUE THREAD

**Issue by bpstrngr** [massivemadness/Squircle-CE#186]
could be that i'm just missing something, but it is a valid private key file actually. 

**App Version:**
latest

**Affected Device(s):**
Samsung note 10 lite with Android 13.0

**Describe the bug**
invalid privatekey after passphrase input

**To Reproduce**
1. add a new sftp server and provide private key path (termux home directory wasn't accessible so i copied it to storage/emulated/0/Download/id_rsa and chmod 700-ed it)
2. select the server in the fike explorer sidebar and privide passphrase on prompt
3. see error message "invalid privatekey: [B@dd2exxd"

**Expected behavior**
successful authentication

**Comment by massivemadness** [comment]
I guess I'm just using outdated library that can't handle your key.
If you know how the algorithm works you can help me figure it out 😄 ([1](https://github.com/is/jsch/blob/master/src/main/java/com/jcraft/jsch/KeyPair.java#L213), [2](https://github.com/is/jsch/blob/master/src/main/java/com/jcraft/jsch/KeyPair.java#L241), [3](https://github.com/is/jsch/blob/master/src/main/java/com/jcraft/jsch/KeyPair.java#L331), [4](https://github.com/is/jsch/blob/master/src/main/java/com/jcraft/jsch/KeyPair.java#L343), [5](https://github.com/is/jsch/blob/master/src/main/java/com/jcraft/jsch/KeyPair.java#L616))
I can make an experimental build for you if you have time to test it

**Comment by massivemadness** [comment]
There's a [fork](https://github.com/mwiede/jsch) that is being updated, but I could try to fully switch to [sshj](https://github.com/hierynomus/sshj) 🤔
Anyway I'll text you here when the build will be ready

**Comment by massivemadness** [comment]
Hi @bpstrngr, try this build - [4588280564](https://github.com/massivemadness/Squircle-CE/actions/runs/4588280564)

**Comment by bpstrngr** [comment]
i checked out the build, issue persists. :/

**Comment by massivemadness** [comment]
I just checked it, should be fixed now ([4620884875](https://github.com/massivemadness/Squircle-CE/actions/runs/4620884875))

**Comment by jnguk** [comment]
Maybe you should generate PEM format key, executing `ssh-keygen` with `-m pem` option.
But you have to remove `.pem` extension. See https://github.com/massivemadness/Squircle-CE/issues/180#issuecomment-1479268466 .

**Comment by massivemadness** [comment]
Fixed in [v2023.1.4](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.4)
