### ISSUE TITLE
Can't create files from the explorer panel

### ISSUE THREAD

**Issue by xparq** [massivemadness/Squircle-CE#194]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
2023.1.4

**Affected Device(s):**

Huawei Mate 10 Pro (not rooted) with Android 10.0 (+ MEUI 10, and Microsoft Launcher(?))

** Description **

Right after a fresh install (today), and opening it the first time, it consistently failed to create any new files from its file explorer / folder selector tool, for some strange reason.

Storage perm. granted, "Documents" folder selected (or same with "Downloads"), default "untitled.txt" (or any other name/ext. I tried): "An error occured"...

Some more detailed error message also seemed to pop up right beforehand, but it always disappeared immediately, so I had no chance reading or capturing that.

Other apps could of course write there just fine. 

This app could still open those files created with something else, and then Save works just fine. Moreover, even Save As, or New works, too, from inside the editor's File menu, so it seems the problem is (fortunately) confined to the "explorer" tool.

**Comment by massivemadness** [comment]
Hi @xparq, the only validation for filename is `isNotEmpty() && !contains("/") && !equals(".") && !equals("..")`. It looks like you're getting an error thrown by the android framework 🥴
I need some time to investigate this, thanks for reporting

**Comment by xparq** [comment]
Hey @massivemadness, thanks for checking!

Very bizarre indeed, I have zero idea what could interfere there.
