### ISSUE TITLE
Can't changes things in the Storage!

### ISSUE THREAD

**Issue by Dilihapu** [massivemadness/Squircle-CE#199]
App Version:2023.1.4 on Android 11

Can't create a new folder & a new file and not paste after copy and cut a file or a folder. It is also not possible to the rename. Shows with an error message about it ("an error occurred").

The Phone storage is not support to changes! (No sure)
Please, explain a wrong what & fix it…
Thank you!

**Comment by massivemadness** [comment]
Sounds like `MANAGE_EXTERNAL_STORAGE` permission is missing. Did you grant it on the first launch?

**Comment by Dilihapu** [comment]
> Sounds like `MANAGE_EXTERNAL_STORAGE` permission is missing. Did you grant it on the first launch?

Yes, I gave permissions! I use old version (2023.1.3) because that problem.

**Comment by massivemadness** [comment]
Hi @Dilihapu, I added more detailed error messages, try this build - [5235261974](https://github.com/massivemadness/Squircle-CE/actions/runs/5235261974). What error are you getting?

**Comment by massivemadness** [comment]
I uploaded the patch in google play, it takes about a day or two to publish, you can download it right now on GitHub (https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.5)
