### ISSUE TITLE
Can't changes everything in storage!

### ISSUE THREAD

**Issue by Dilihapu** [massivemadness/Squircle-CE#207]
Hi!
You released (2023.1.5) that bug fix not yet.
Can't create a file, pasting & renaming.
It's coming an error like this screenshot!

Thank you!
![Screenshot_20230705-083505](https://github.com/massivemadness/Squircle-CE/assets/125900049/cc1b4f59-5617-4efd-87b6-96c44bc50e08)

**Comment by massivemadness** [comment]
Hi @Dilihapu, I fixed this issue in Google Play version and published on GitHub [releases page](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.5) 🤔
If you're using F-Droid version then it probably doesn't contain this fix.
Can you take a screenshot of Settings > About page?

**Comment by Dilihapu** [comment]
![Screenshot_20230705-144319](https://github.com/massivemadness/Squircle-CE/assets/125900049/14f27926-79fc-444d-9363-e0cdf43e8ba4)

**Comment by massivemadness** [comment]
I mean in the app settings, there is a version name + code version

**Comment by Dilihapu** [comment]
![Uploading Screenshot_20230705-160648.png…]()

**Comment by Dilihapu** [comment]
![Uploading Screenshot_20230705-160648.png…]()

**Comment by Dilihapu** [comment]
![Uploading Screenshot_20230705-160648.png…]()

**Comment by Dilihapu** [comment]
![Screenshot_20230705-160648](https://github.com/massivemadness/Squircle-CE/assets/125900049/a69626f5-3624-4543-9d9d-1de1056f6633)

**Comment by massivemadness** [comment]
Yep, that's an old version without fix. Since then 2 patches have been released, you can download the latest version (10021) on the GitHub [release page](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.5) or Google Play
