### ISSUE TITLE
Sinhala (Sri Lanka) Language support.

### ISSUE THREAD

**Issue by Dilihapu** [massivemadness/Squircle-CE#208]
Hello, dima!
You provided link is not available Sinhala Language!
I would like translate to Sinhala Squirrel CE App. So' please give me the language order (xml, json) if you can. If you provide that I can translate in offline. Then it's easy for me. 

Thanks!

**Comment by massivemadness** [comment]
Hi, thanks for letting me know, I just added the Sinhala language to crowdin 🙆‍♂️
Offline translation is not recommended because it requires some additional work from me to sync it with localization platform
