### ISSUE TITLE
Unable to create new file

### ISSUE THREAD

**Issue by hjek** [massivemadness/Squircle-CE#224]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
2023.1.5

**Affected Device(s):**
Nokia 2.2

**Describe the bug**
Unable to create new file. Opening existing files and saving works fine.

**To Reproduce**
1. Open Squircle file explorer and press `+`
2. Enter file name, `hello.txt`, and tap **Create**
3. Error message pops up. No new file created.

https://github.com/massivemadness/Squircle-CE/assets/11958965/66838afd-0dc8-48e0-95f5-6524246b7dd5

**Expected behavior**
I expected `hello.txt` to be created and opened in editor tab.

**Comment by massivemadness** [comment]
Hi @hjek, can you please try the [latest](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.2.0) version?

**Comment by massivemadness** [comment]
Hi @hjek, can you please try this [patch.zip](https://github.com/massivemadness/Squircle-CE/files/13355585/patch.zip)? There is an apk inside, if it's working then I'll release a hotfix

**Comment by hjek** [comment]
Works in latest version. Thanks!
