### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by lunaticsm** [massivemadness/Squircle-CE#250]
We still wait for an update. best app i had since 1 year ago.

**Comment by massivemadness** [comment]
Hello, unfortunately the app is abandoned for now. I've added more details in this issue https://github.com/massivemadness/Squircle-CE/issues/249

**Comment by massivemadness** [comment]
Hey, quick update - the app is back on Google Play (I had to create a new developer account and make a transfer request, but that's the only way to return it to store) and I'm already working on a new update, many improvements are coming! 🤞

**Comment by lunaticsm** [comment]
Good to hear that. cause since now i always use this app.
