### ISSUE TITLE
Extended Keyboard Fullscreen

### ISSUE THREAD

**Issue by Kundarageze** [massivemadness/Squircle-CE#35]
**App Version:**
2020.3.1 Standard Edition

**Affected Device(s):**
LG with Android 8.1

**Describe the bug**
The extended keyboard in fullscreen does not show up

**Comment by massivemadness** [comment]
That's an android issue - the extended keyboard is actually appears in fullscreen mode, but it's behind your input keyboard

https://issuetracker.google.com/issues/36911528

That's an old bug and there is no workarounds, so it probably will not be fixed 😞

**Comment by Kundarageze** [comment]
Well I guess we will have to deal with it then. Thank you for your time

**Comment by massivemadness** [comment]
Fixed in [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.1)
