### ISSUE TITLE
Force Syntax Highlighting

### ISSUE THREAD

**Issue by tuftkyle** [massivemadness/Squircle-CE#68]
**Problem**
App defaults to plaintext when it doesn't recognize the file extension.

**Solution**
Add an option to force syntax highlighting for a particular file you open, with the added option to open all files with that extension using that syntax.

**Alternatives**
For now I can change the extension to what I want (e.g. JSON, XML) and just change it back when I'm done. It would be great to not need to do that though!

**Comment by massivemadness** [comment]
7d79437e36edffb4e72f9388d3f95c4d611a2ff5
