### ISSUE TITLE
Support Storage Access Framework standard

### ISSUE THREAD

**Issue by J4gQBqqR** [massivemadness/Squircle-CE#70]
**Is your feature request related to a problem? Please describe.**
A SAF support will be useful in the following situation:
1. automatically sync code with cloud solution such as Nextcloud.
2. open file with SFTP mounted SAF folder on a remote Linux server.

**Describe the solution you'd like**
Be able to open file with SAF mounted storage.

**Describe alternatives you've considered**
Be able to use SFTP to open file on a remote server.

**Additional context**
Could refer to Nextcloud code for SAF implementation. Could refer to VLC code for SFTP implementation.

**Comment by nikey02** [comment]
+1 for this
also by adding SFA we can edit files from termux 
I'm excited about this 
please add SFA ASAP🥳

**Comment by J4gQBqqR** [comment]
Another place to find SFA implementation is the Aegis authenticator.

**Comment by J4gQBqqR** [comment]
Google is enforcing SFA as the **only method** to access shared storage in the future Android release.

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by massivemadness** [comment]
SFTP support was added in v2022.2.0
d3f08c39e8b6e2c3cd359368eb998d41ee9b6796
SAF will not be implemented

**Comment by massivemadness** [comment]
Added in [v2023.1.2](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.2)

**Comment by john-peterson** [comment]
gh search issues --json title,number  -R massivemadness/Squircle-CE saf

# SAF providers give EACCESS or No such file or directory

is saf supported at all. is this a bug or lack of feature 

open file uses the saf dialogue but it seems like it's trying to convert all saf paths content://... to regular paths

Downloads/abc/abc.txt is nearly correct but missing subfolder

~~~
No such file or directory (/storage.../Downloads/abc.txt
~~~

content://org.app/tree/blabla/abc.txt translates to root folder? path conversion failed completely?

~~~
/: open failed EACCESS
~~~

**Comment by KaKi87** [comment]
This app looks dead anyway
