### ISSUE TITLE
Add the option to open files with SAF on android and save with same

### ISSUE THREAD

**Issue by esp2019** [massivemadness/Squircle-CE#77]
I cant save documents that i am editing from microsd card beacuse the access is denied to save on external storage.

**Comment by LNDEVIL** [comment]
Still a very important feature

**Comment by massivemadness** [comment]
SAF will not be implemented, but support for microSD is planned #120

**Comment by massivemadness** [comment]
Added in [v2023.1.2](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.2)
